permalink: pretty
markdown: kramdown
title: Two Factor Auth
description:
  List of sites with Two Factor Auth support which includes SMS, email,
  phone calls, hardware, and software.
url: https://2fa.directory
twitter: 2faorg
social_image: https://repository-images.githubusercontent.com/17724730/63495880-b408-11e9-8cc4-03451aa4cc14
theme_color: "#39CCCC"
exclude:
  - EXCLUSION.md
  - Gemfile
  - *.lock
  - LICENSE
  - README.md
  - Rakefile
  - vendor/
  - scripts/
  - tests/
  - api/v2/README.md
  - .*
theme: null
